# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_d5a0f92b01a5271921641b5e0845f100950cbabf

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client

# Exclude test files
sonar.exclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts
