# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_d5a0f92b01a5271921641b5e0845f100950cbabf

# Project identification
sonar.projectKey=team08
sonar.projectName=team08
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client/src,controllers,models,config,middlewares,helpers

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.inclusions=client/src/context/auth.js,client/src/context/search.js,client/src/context/cart.js,client/src/components/AdminMenu.js,client/src/components/Form/CategoryForm.js,client/src/components/Form/SearchInput.js,client/src/components/Routes/Private.js,client/src/components/UserMenu.js,client/src/components/Footer.js,client/src/components/Header.js,client/src/components/Layout.js,client/src/components/Spinner.js,client/src/pages/Auth/Register.js,client/src/pages/Auth/Login.js,client/src/pages/admin/AdminDashboard.js,client/src/pages/admin/CreateCategory.js,client/src/pages/admin/CreateProduct.js,client/src/pages/admin/UpdateProduct.js,client/src/pages/admin/AdminOrders.js,client/src/pages/admin/Products.js,client/src/pages/admin/Users.js,client/src/pages/user/Dashboard.js,client/src/pages/user/Orders.js,client/src/pages/user/Profile.js,client/src/pages/Search.js,client/src/pages/ProductDetails.js,client/src/pages/CategoryProduct.js,client/src/pages/Contact.js,client/src/pages/Policy.js,client/src/pages/About.js,client/src/pages/Pagenotfound.js,client/src/pages/HomePage.js,client/src/pages/CartPage.js,client/src/hooks/useCategory.js,client/src/pages/Categories.js,helpers/authHelper.js,middlewares/authMiddleware.js,controllers/authController.js,controllers/categoryController.js,controllers/productController.js,models/userModel.js,models/orderModel.js,models/productModel.js,models/categoryModel.js,config/db.js
sonar.exclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,*.css,index.js,reportWebVitals.js,setupTests.js,index.html
