# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_d5a0f92b01a5271921641b5e0845f100950cbabf

# Project identification
sonar.projectKey=team08
sonar.projectName=team08
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client/src,controllers,models,routes,config,middlewares,helpers,server.js

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude test files
sonar.exclusions=**/*.test.js,**/*.spec.js,**/*.test.ts,**/*.spec.ts,*.css,App.js,index.js,reportWebVitals.js,setupTests.js,index.html
